[package]
name = "sled-jimtcl"
version = "0.1.0"
authors = ["Coleman McFarland <coleman.mcfarland@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
sled = "*"
bincode = "*"

[build-dependencies]
bindgen = "*"
